### ISSUE TITLE
Odditites with activeScanningAreaPortrait setting for Android.

### ISSUE THREAD

**Issue by nnitrx** [Scandit/barcodescanner-sdk-react-native#110]
In our app, we're been trying to match our scanning area with the dimensions displayed on our custom overlay.  The area will stay consistent to the rect defined for iOS, but for Android, I can't seem to move the area anywhere from the center of the screen. Right now on Android I have the Rect defined as:

new Rect(0.2, 0.1, 0.2, 0.1)

This seems to consistently cover about 20% width 10% height of the center of the screen, but will also scan something from the top left corner, as if there are 2 scanning areas.  Whenever I give the x/y coords higher percentages the center scanning area seems to grow considerably to where I can't seem to tell what's being covered.  I've tried fiddling with the flex properties, along with removing all other components in the view the scanner is being referenced but I'm still getting the same behavior.  Our settings are being set programmatically through applySettings upon mount as well as through an app state change listener.

**Comment by moritzhartmeier** [comment]
What kind of codes are you scanning? There is a special case for 2d codes (like qr, datamatrix) where if the height is 0.1 or below it will only count for 1d codes but 2d codes are scanned in the entire screen again.
0.1 and below in height is also behaves a bit differently in terms of restriction that it restricts a bit more, so that the difference between 0.1 and 0.11 is larger than any 0.01 jump is normally.

It would be good to know what your exact use case is, what kind of codes you are scanning and what your restriction needs are.

**Comment by nnitrx** [comment]
We're strictly only looking for datamatrix codes, it's the only symbology that's enabled.  We're only allowing one code per frame, with the duplicate filter set to -1.  There's a two step process involving the scanning of a different datamatrix each step.  We want the scan area to be placed slightly above the center due to a dialog being placed along the bottom of the screen.  On iOS we have the rect set as:
new Rect(0.45, 0.25, 0.1, 0.1),
which works consistently on that platform, however for Android this setting gives a much broader range than defined and seems to always originate from the center.  I've tried setting the width and height to 0.11 on the defined rect above and it seems to now scan consistently in the area defined, however it also seems to scan at the same width + height in the dead center of the screen as well.

**Comment by moritzhartmeier** [comment]
The underlying logic for these settings are in shared C++ code which is why this should be behaving the same on iOS and Android (with potential exception of minor changes because of different frame aspect ratio). We have not heard of any similar problems before but will have a look in the coming weeks. For now I can only suggest leaving it centered.

It would help us a lot with investigating the issue if you could copy paste the exact settings that you use here.
