### ISSUE TITLE
Issues when used with react-native-camera

### ISSUE THREAD

**Issue by fmonsalvo** [Scandit/barcodescanner-sdk-react-native#145]
When used in a project containing react-native-camera there's a re-register of the onTextRecognized event. RN Camera defines it as a RCTDirectEventBlock while Scandit declares it as RCTBubblingEventBlock.
is there any way around this issue?

**Comment by petradonka** [comment]
Hey @fmonsalvo,

Could you provide us with some more info on the issue you're experiencing? I understand you have a project with both the react-native-camera and the Scandit plugin. We're currently not aware of any issues related to this, could you tell us more about what exactly happens when you use them together and what you'd expect to happen? If possible and relevant, some code that triggers this issue would help us a lot too.

**Comment by fmonsalvo** [comment]
Hey @petradonka what is happening is that my app won't start since both project register the same event with different types.
![IMG_AB810163CAD3-1](https://user-images.githubusercontent.com/610463/57319662-7c758e00-70d3-11e9-9520-de4e1bc82b87.jpeg)

Hope the screenshot help clarifying the issue. What's happening is that React-Native-Camera registers the event as RCTDirectEventBlock and Scandit registers it as RCTBubblingEventBlock.
This is not allowed in React-Native and the app won't event start.
I can fix it by changing the registration to RCTDirectEventBlock in Scandit or RCTBubblingEventBlock in React-Native-Camera, but I'll need to fork one of the projects and I would not like to do so as maintaining the fork will get messy and I believe this could be easily solved on your side.

**Comment by petradonka** [comment]
Thanks for getting back to us, we now fixed this on branches _master_ and _5.11_, you can pull directly from there or wait for the next official release.
