### ISSUE TITLE
Linking issues with react-native 59 using Pods

### ISSUE THREAD

**Issue by wojteg1337** [Scandit/barcodescanner-sdk-react-native#189]
I wanted to link the library with pods but with no success. Could you add the steps for pods integration?

**Comment by petradonka** [comment]
You could take a look at https://github.com/Scandit/barcodescanner-sdk-react-native/blob/master/docs/howto-upgrade.md and see if you can find the info you need, otherwise we'd need more information about how you're trying to use our library with pods, support@scandit.com would be able to help figure that out.

**Comment by wojteg1337** [comment]
I'm using react-native 0.59.8 and scandit-react-native 5.13.0 / 5.13.1. I'm unable to link library... When trying to link library manually within the project, the library does not find React -React is linked with pods. When trying to link library with pods i'm unable to see the Scandit-SDK. Is it possible to find somewhere steps about pods integration?

**Comment by petradonka** [comment]
We'd like to get to know more about the project you're working on, it'd be best if you'd send a quick email to support@scandit.com so we can help you with this.
