### ISSUE TITLE
Execution failed for task ':scandit-react-native:compileDebugKotlin'.

### ISSUE THREAD

**Issue by jmorey28** [Scandit/barcodescanner-sdk-react-native#241]
Getting error Execution failed for task ':scandit-react-native:compileDebugKotlin'. on version 5.19.3. It looks like you have kotlin_version set to 1.3.71 which causes issues in projects using higher versions.

command ran:
react-native run-android --appIdSuffix testing --main-activity com.zoontek.rnbootsplash.RNBootSplashActivity

React Native version 0.68.2

**Comment by ScanditSupport** [comment]
Hi @jmorey28 

Facebook has released a fix for this issue: https://github.com/facebook/react-native/issues/35210
Could you please check if updating to 0.68.5 would resolve the issue for you?

If the issue persists, please get in contact with us directly via: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by jmorey28** [comment]
@ScanditSupport This issue still exists even after the RN upgrade. The only way I am able to fix it is if I apply a patch to your build.gradle file with the following:

ext.kotlin_version = '1.7.20'

**Comment by ScanditSupport** [comment]
Hi @jmorey28,

My apologies, I have missed the fact that you are using the BarcodeScanner React-Native SDK.
Please note that [5.x BarcodeScanner SDK has been deprecated since April 2021.](https://docs.scandit.com/5.19/react_native/index.html)

We would highly recommend using our contemporary 6.x DataCapture SDK which provides a vast array of new features as well as performance and stability improvements:
https://docs.scandit.com/data-capture-sdk/react-native

If you have any questions regarding 6.x DataCapture SDK - please get in contact with us directly via: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
